### ISSUE TITLE
Support for MQTT authentication

### ISSUE THREAD

**Issue by mshuflin** [edward3h/minecraft-webhook#40]
Is there support for a MQTT server that requires authentication? or only one with "allow_anonymous" set to true?

**Comment by edward3h** [comment]
It uses [Micronaut MQTT v5](https://micronaut-projects.github.io/micronaut-mqtt/latest/guide/#v5), so it should work if you add to the mqtt configuration like this:

```yml
mqtt:
  client:
    client-id: mc-webhook
    server-uri: tcp://messages:1883
    user-name: user
    password: 12345
```

I haven't tried it. Let me know if this works for you and I'll do more research if it doesn't.
